const ResList = [
  {
    restaurantName: "Pizza Paradise",
    imageUrl: "https://example.com/pizza.jpg",
    cuisine: ["Italian", "Pizza", "Fast Food"],
    rating: 4.5,
    numberOfRatings: 1200,
    deliveryTime: "30 mins",
    priceForTwo: "₹400",
    discount: "20% OFF",
    offers: ["Free Delivery", "50% OFF on First Order"],
    location: "MG Road, Bangalore",
    isVegetarian: false,
    hasPureVegOptions: true,
    speciality: ["Wood-fired Pizzas", "Garlic Bread"],
    deliveryFee: "₹20",
    isFavorite: false,
  },
  {
    restaurantName: "Sushi Express",
    imageUrl: "https://example.com/sushi.jpg",
    cuisine: ["Japanese", "Sushi", "Seafood"],
    rating: 4.8,
    numberOfRatings: 980,
    deliveryTime: "25 mins",
    priceForTwo: "₹700",
    discount: "10% OFF",
    offers: ["25% OFF on orders above ₹1000"],
    location: "Koramangala, Bangalore",
    isVegetarian: false,
    hasPureVegOptions: false,
    speciality: ["Salmon Sushi", "California Roll"],
    deliveryFee: "₹30",
    isFavorite: true,
  },
  {
    restaurantName: "Green Bites",
    imageUrl: "https://example.com/salad.jpg",
    cuisine: ["Healthy", "Salads", "Vegan"],
    rating: 4.2,
    numberOfRatings: 650,
    deliveryTime: "20 mins",
    priceForTwo: "₹300",
    discount: "30% OFF",
    offers: ["Free Dessert on orders above ₹500"],
    location: "Indiranagar, Bangalore",
    isVegetarian: true,
    hasPureVegOptions: true,
    speciality: ["Kale Salad", "Quinoa Bowl"],
    deliveryFee: "Free",
    isFavorite: false,
  },
  {
    restaurantName: "Tandoori Flames",
    imageUrl: "https://example.com/tandoori.jpg",
    cuisine: ["Indian", "Tandoor", "BBQ"],
    rating: 4.6,
    numberOfRatings: 1150,
    deliveryTime: "35 mins",
    priceForTwo: "₹500",
    discount: "15% OFF",
    offers: ["10% Cashback"],
    location: "Whitefield, Bangalore",
    isVegetarian: false,
    hasPureVegOptions: false,
    speciality: ["Tandoori Chicken", "Paneer Tikka"],
    deliveryFee: "₹25",
    isFavorite: false,
  },
  {
    restaurantName: "Burger Hub",
    imageUrl: "https://example.com/burger.jpg",
    cuisine: ["Fast Food", "Burgers", "American"],
    rating: 4.0,
    numberOfRatings: 900,
    deliveryTime: "20 mins",
    priceForTwo: "₹350",
    discount: "40% OFF",
    offers: ["Combo Deals"],
    location: "JP Nagar, Bangalore",
    isVegetarian: false,
    hasPureVegOptions: true,
    speciality: ["Cheeseburger", "Fries"],
    deliveryFee: "₹15",
    isFavorite: true,
  },
  {
    restaurantName: "Wok This Way",
    imageUrl: "https://example.com/wok.jpg",
    cuisine: ["Asian", "Chinese", "Thai"],
    rating: 4.3,
    numberOfRatings: 700,
    deliveryTime: "30 mins",
    priceForTwo: "₹450",
    discount: "20% OFF",
    offers: ["20% OFF on orders above ₹800"],
    location: "HSR Layout, Bangalore",
    isVegetarian: false,
    hasPureVegOptions: true,
    speciality: ["Pad Thai", "Kung Pao Chicken"],
    deliveryFee: "₹20",
    isFavorite: false,
  },
  {
    restaurantName: "Pasta Mania",
    imageUrl: "https://example.com/pasta.jpg",
    cuisine: ["Italian", "Pasta"],
    rating: 4.4,
    numberOfRatings: 800,
    deliveryTime: "25 mins",
    priceForTwo: "₹500",
    discount: "25% OFF",
    offers: ["Free Garlic Bread"],
    location: "BTM Layout, Bangalore",
    isVegetarian: true,
    hasPureVegOptions: true,
    speciality: ["Spaghetti Carbonara", "Penne Arrabbiata"],
    deliveryFee: "₹20",
    isFavorite: true,
  },
  {
    restaurantName: "Desi Dhaba",
    imageUrl: "https://example.com/dhaba.jpg",
    cuisine: ["Indian", "Punjabi"],
    rating: 4.7,
    numberOfRatings: 1400,
    deliveryTime: "40 mins",
    priceForTwo: "₹600",
    discount: "20% OFF",
    offers: ["Buy 1 Get 1 Free"],
    location: "Yeshwanthpur, Bangalore",
    isVegetarian: false,
    hasPureVegOptions: true,
    speciality: ["Butter Chicken", "Paneer Butter Masala"],
    deliveryFee: "₹25",
    isFavorite: false,
  },
  {
    restaurantName: "Wrap & Roll",
    imageUrl: "https://example.com/wrap.jpg",
    cuisine: ["Fast Food", "Wraps", "Rolls"],
    rating: 4.2,
    numberOfRatings: 500,
    deliveryTime: "15 mins",
    priceForTwo: "₹250",
    discount: "10% OFF",
    offers: ["Free Drink with Wrap"],
    location: "Koramangala, Bangalore",
    isVegetarian: false,
    hasPureVegOptions: true,
    speciality: ["Chicken Kathi Roll", "Paneer Roll"],
    deliveryFee: "₹10",
    isFavorite: true,
  },
  {
    restaurantName: "Momo Street",
    imageUrl: "https://example.com/momo.jpg",
    cuisine: ["Asian", "Tibetan", "Snacks"],
    rating: 4.1,
    numberOfRatings: 620,
    deliveryTime: "20 mins",
    priceForTwo: "₹200",
    discount: "15% OFF",
    offers: ["Free Dip"],
    location: "MG Road, Bangalore",
    isVegetarian: false,
    hasPureVegOptions: true,
    speciality: ["Steamed Momos", "Fried Momos"],
    deliveryFee: "₹5",
    isFavorite: false,
  },
  {
    restaurantName: "South Spice",
    imageUrl: "https://example.com/south.jpg",
    cuisine: ["South Indian", "Vegetarian"],
    rating: 4.6,
    numberOfRatings: 1100,
    deliveryTime: "25 mins",
    priceForTwo: "₹300",
    discount: "20% OFF",
    offers: ["20% OFF on Dosa Combo"],
    location: "Basavanagudi, Bangalore",
    isVegetarian: true,
    hasPureVegOptions: true,
    speciality: ["Masala Dosa", "Idli Vada"],
    deliveryFee: "₹10",
    isFavorite: true,
  },
  {
    restaurantName: "Taco Town",
    imageUrl: "https://example.com/taco.jpg",
    cuisine: ["Mexican", "Fast Food"],
    rating: 4.3,
    numberOfRatings: 800,
    deliveryTime: "30 mins",
    priceForTwo: "₹450",
    discount: "25% OFF",
    offers: ["Free Nachos"],
    location: "Indiranagar, Bangalore",
    isVegetarian: false,
    hasPureVegOptions: true,
    speciality: ["Tacos", "Burritos"],
    deliveryFee: "₹20",
    isFavorite: false,
  },
  {
    restaurantName: "Dessert Corner",
    imageUrl: "https://example.com/dessert.jpg",
    cuisine: ["Desserts", "Bakery", "Cafe"],
    rating: 4.7,
    numberOfRatings: 950,
    deliveryTime: "20 mins",
    priceForTwo: "₹250",
    discount: "10% OFF",
    offers: ["Free Pastry with Order"],
    location: "Brigade Road, Bangalore",
    isVegetarian: true,
    hasPureVegOptions: true,
    speciality: ["Chocolate Cake", "Cheesecake"],
    deliveryFee: "₹15",
    isFavorite: false,
  },
  {
    restaurantName: "BBQ Central",
    imageUrl: "https://example.com/bbq.jpg",
    cuisine: ["Grill", "BBQ", "American"],
    rating: 4.5,
    numberOfRatings: 1300,
    deliveryTime: "35 mins",
    priceForTwo: "₹650",
    discount: "20% OFF",
    offers: ["BBQ Platter Discount"],
    location: "Banashankari, Bangalore",
    isVegetarian: false,
    hasPureVegOptions: false,
    speciality: ["BBQ Ribs", "Pulled Pork"],
    deliveryFee: "₹30",
    isFavorite: false,
  },
  {
    restaurantName: "Cafe Bloom",
    imageUrl: "https://example.com/cafe.jpg",
    cuisine: ["Cafe", "Continental", "Beverages"],
    rating: 4.0,
    numberOfRatings: 400,
    deliveryTime: "15 mins",
    priceForTwo: "₹300",
    discount: "5% OFF",
    offers: ["Free Coffee with Brunch"],
    location: "Ulsoor, Bangalore",
    isVegetarian: true,
    hasPureVegOptions: true,
    speciality: ["Pancakes", "Coffee"],
    deliveryFee: "Free",
    isFavorite: true,
  },
];

export default ResList;
